### ISSUE TITLE
BBC: Bleadperl v5.41.3 breaks Data-Hopen-0.000019 (due smartmatch removal)

### ISSUE THREAD

**Issue by andk** [hopenbuild/Data-Hopen#6]
Sample fail report: http://www.cpantesters.org/cpan/report/2eda67aa-6c50-11ef-b9cb-b4200831f901

**Comment by cxw42** [comment]
Thanks for the report!  Will update.

**Comment by cxw42** [comment]
@andk I will post a TRIAL release in the next day or two --- I am switching this project over to Minilla first :) .  Thanks again!

**Comment by cxw42** [comment]
0.000020-TRIAL released
